# Generated by Django 4.2.7 on 2023-11-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenantdocument_tenant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('Security', 'security'), ('Rent', 'rent'), ('Mess', 'mess'), ('utility', 'utility')], max_length=20)),
                ('remarks', models.TextField()),
                ('payment_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_untill', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
