# Generated by Django 4.2.7 on 2023-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdocument',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
