# Generated by Django 4.2.7 on 2023-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantdocument_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('student', 'student'), ('job holder', 'job holder')], default='student', max_length=20),
            preserve_default=False,
        ),
    ]
