# Generated by Django 4.2.7 on 2023-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdocument',
            name='tenant_type',
            field=models.CharField(choices=[('CNIC', 'CNIC'), ('PASSPORT', 'Passport')], default='student', max_length=20),
            preserve_default=False,
        ),
    ]
