# Generated by Django 4.2.7 on 2023-12-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantdocument_tenant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantdocument',
            old_name='tenent',
            new_name='tenant',
        ),
    ]
