# Generated by Django 4.2.7 on 2023-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hostel_address', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now=True)),
                ('modifide_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('number_of_seats', models.IntegerField()),
                ('attached_washroom', models.BooleanField()),
                ('remarks', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modifide_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
